version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "Зависимости:"
    groups:
      spring:
        patterns:
          - "org.springframework*"
      aws:
        patterns:
          - "software.amazon.awssdk:*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "Actions:"
